volumes:
  redis_data:
services:
  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes
    # persistent storage
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  storyville:
    image: storyville:0.1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CACHE_URL=redis://redis:6379/0
      - SECRET_KEY=Not a secret! Do not use in production!
      - ALLOWED_HOSTS=*
      - SITE_ID=3
    depends_on:
      - redis
    volumes:
      - ./var/db:/app/var/db
      - ./var/www:/app/var/www
  caddy:
    image: caddy:2.8.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./var/www:/var/www
    depends_on:
      - storyville
