name: Run test suite
on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build tox tox-gh-actions

      - name: Run the test suite
        run: tox run
